//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_control : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.control_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.control_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Move
        {
            get
            {
                return SteamVR_Actions.control_Move;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.control_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPad
        {
            get
            {
                return SteamVR_Actions.control_TrackPad;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.control_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button1
        {
            get
            {
                return SteamVR_Actions.control_Button1;
            }
        }
        
        public virtual SteamVR_Action_Boolean Button2
        {
            get
            {
                return SteamVR_Actions.control_Button2;
            }
        }
    }
}
